name: IPO Listing Alert (auto-fetch)

on:
  schedule:
    - cron: '0 8 * * 1-5'   # 08:00 UTC = 13:30 IST Mon-Fri
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance requests beautifulsoup4 lxml

      - name: Run auto-fetch IPO script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}         # optional
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }} # optional
          MIN_GAIN: '8'
          MAX_GAIN: '30'
        run: python ipo_alerts_auto.py
